name: Publish to PyPI and Update Backend

on:
  push:
    tags:
      - 'v*'  # Triggered on version tags like v0.1.0, v1.2.3
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.0)'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov build twine
    
    - name: Install package
      run: pip install -e .
    
    - name: Run tests
      run: |
        pytest tests/ --cov=detectors --cov-report=xml
    
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

  publish:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Extract version from tag or input
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/v}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Publishing version: $VERSION"
    
    - name: Update version in __init__.py
      run: |
        sed -i 's/__version__ = ".*"/__version__ = "${{ steps.version.outputs.VERSION }}"/' detectors/__init__.py
        cat detectors/__init__.py | grep __version__
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Publish to TestPyPI (optional)
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        twine upload --repository testpypi dist/* --skip-existing || true
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.VERSION }}
        name: Release v${{ steps.version.outputs.VERSION }}
        body: |
          ## Changes
          
          See [CHANGELOG.md](CHANGELOG.md) for details.
          
          ## Installation
          
          ```bash
          pip install zero-harm-ai-detectors==${{ steps.version.outputs.VERSION }}
          ```
        draft: false
        prerelease: false

  trigger-backend-update:
    needs: publish
    runs-on: ubuntu-latest
    
    steps:
    - name: Extract version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/v}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Wait for PyPI propagation
      run: |
        echo "Waiting 2 minutes for PyPI to propagate the new version..."
        sleep 120
    
    - name: Trigger Backend Update
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.BACKEND_REPO_TOKEN }}
        repository: Zero-Harm-AI-LLC/zero-harm-ai-backend
        event-type: library-updated
        client-payload: |
          {
            "library_version": "${{ steps.version.outputs.VERSION }}",
            "library_name": "zero-harm-ai-detectors"
          }